package vn.gpay.gsmart.core.utils;

public class ColumnPersonnel {
	public static int STT  				= 0;
	public static int MaSoMoi			= 1;
	public static int TinhTrang  		= 2;
	public static int ThoiVu			= 3;
	public static int Ho 				= 4;
	public static int Ten		  		= 5;
	public static int HoVaTen  			= 6;
	public static int GT	  			= 7;
	public static int NgaySinh	  		= 8;
	public static int BoPhan	  		= 9;
	public static int ChucVu		  	= 10;
	public static int ChucVutrongBH		= 11;
	public static int Bac				= 12;
	public static int MaBacluongBH  	= 13;
	public static int HeSoLuongBH		= 14;
	public static int MucLuongDongBH	= 15;
	public static int MucLuongHT  		= 16;
	public static int HeSoCV		  	= 17;
	public static int ThangGiamBH	  	= 18;
	public static int NgayVaoCT  		= 19;
	public static int NgayThoiViec  	= 20;
	public static int LyDo	  			= 21;
	public static int NgayKiHDTV	  	= 22;
	public static int NgayKiHDCTH  		= 23;
	public static int NgayKiHDVTH		= 24;
	public static int NgayDongBH		= 25;
	public static int TGCongTac			= 26;
	public static int Thon				= 27;
	public static int Xa				= 28;
	public static int Huyen				= 29;
	public static int Tinh				= 30;
	public static int DiaChi			= 31;
	public static int DienThoai			= 32;
	public static int CMND				= 33;
	public static int NgayCap			= 34;
	public static int NoiCap			= 35;
	public static int CMTM 				= 36; 
	public static int NgayCapMoi		= 37;
	public static int NoiCapMoi			= 38;
	public static int SucKhoe			= 39;
	public static int SoSBH				= 40;
}
