package vn.gpay.gsmart.core.utils;

public class ColumnPersonnel {
	public static int STT  				= 0;
	public static int MaSoCu			= 1;
	public static int MaSoMoi			= 2;
	public static int TinhTrang  		= 3;
	public static int Ho 				= 4;
	public static int Ten		  		= 5;
	public static int HoVaTen  			= 6;
	public static int GT	  			= 7;
	public static int NgaySinh	  		= 8;
	public static int Tuoi	  			= 9;
	public static int BoPhan	  		= 10;
	public static int ChucVu		  	= 11;
	public static int ChucVutrongBH		= 12;
	public static int Bac				= 13;
	public static int MaBacluongBH  	= 14;
	public static int HeSoLuongBH		= 15;
	public static int MucLuongDongBH	= 16;
	public static int MucLuongHT  		= 17;
	public static int HeSoCV		  	= 18;
	public static int ThangGiamBH	  	= 19;
	public static int NgayVaoCT  		= 20;
	public static int NgayThoiViec  	= 21;
	public static int LyDo	  			= 22;
	public static int NgayKiHDTV	  	= 23;
	public static int NgayKiHDCTH  		= 24;
	public static int NgayKiHDVTH		= 25;
	public static int NgayDongBH		= 26;
	public static int TGCongTac			= 27;
	public static int Thon				= 28;
	public static int Xa				= 29;
	public static int Huyen				= 30;
	public static int Tinh				= 31;
	public static int DiaChi			= 32;
	public static int DienThoai			= 33;
	public static int CMND				= 34;
	public static int NgayCap			= 35;
	public static int NoiCap			= 36;
	public static int CMTM 				= 37; 
	public static int NgayCapMoi		= 38;
	public static int NoiCapMoi			= 39;
	public static int SucKhoe			= 40;
	public static int SoSBH				= 41;
}
